name: CI/CD Workflow

on:
  push:
    branches:
      - '**'  # This will match all branches
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests
      env:  # Setting up the environment variables
        RUNNING_IN_GITHUB: true
        FANART_API_KEY: ${{ secrets.FANART_API_KEY }}
      run: pytest

  deploy:
    needs: testing
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: media-djinn
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy art-getter \
        --entry-point get_art \
        --runtime python310 \
        --trigger-http \
        --allow-unauthenticated \
        --region us-west1 \
        --project media-djinn
