name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run tests
      run: pytest

  deploy:
    needs: testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Google Cloud Functions
      uses: google-github-actions/deploy-cloud-functions@v1
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        project_id: media-djinn
        region: us-west1  # specify the region you want to deploy to, e.g., us-central1
        name: get_art
        entry_point: get_art
        runtime: python310
        source_dir: .   # This assumes that your main.py is in the root of your repo
        trigger: http
        allow_unauthenticated: true
